name: google_maps_iframe
version: 0.1.1
author: Graciliano Monteiro Passos <gracilianomp@gmail.com>
description: A wrapper for Google Maps JS API inside a iframe.
homepage: https://github.com/UpLibs/google_maps_iframe
